### ISSUE TITLE
the day and year is Reversed when the label lang is ar in iOS and Android

### ISSUE THREAD

**Issue by IbrahimSalem0** [y471n/react-native-hijri-date-picker#6]
thanks for providing this lib, it's help me as I was looking for something like that exactly 

I'm trying to use the lib and when I set the labelLang prop to ar it shows num reversed In the datePicker, 

removing 
`    .reverse()
`
it fixes the problem. so it can u help. 

another thing , when I set endYear it's make the years order from the last year I have set , it should open on the start year not the last.

and also , is there any opportunity to set the initial  date for the picker not just the year, 

I'm trying to make the picker open on the initial date and updated depend on the value have sent, because it's open always on the first day and first month of the start year I have set even if I send the date like this momentHijri 1446/02/26 

 <HijriRNDatePicker
            updateDate={handleDateChange}
            mode="inline"
            labelLang={i18n.language === 'ar' ? 'ar' : 'en'}
            valueLang={'en'}
            initialParams={{
              startYear: parseInt(momentHijri().format('iYYYY')),
              endYear: maxDate ? parseInt(maxDate.format('iYYYY')) : undefined,
            }}
          /> 

<img width="378" alt="Screenshot 2024-08-30 at 9 57 52 PM" src="https://github.com/user-attachments/assets/31660f40-f7bb-4681-a3e2-753c79a3bcd4">

**Comment by y471n** [comment]
Thanks @IbrahimSalem0 for testing. Will address your comments this week.
